name: Convert LaTeX CV to Image and Publish on EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Convert LaTeX to Image
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive imagemagick
          sudo apt-get install texlive-publishers
          sudo apt-get install texlive-fonts-extra
          sudo apt-get install poppler-utils
          wget https://raw.githubusercontent.com/tunahanyilmazz/devops_cv/main/main.tex
          pdflatex -halt-on-error -interaction=batchmode main.tex || true
          pdftoppm -png -r 300 main.pdf main
          mv main-1.png main.png
          rm main.tex main.pdf
          
      - name: Set Permissions on Remote Server
        uses: appleboy/ssh-action@master
        with:
          host: ec2-16-16-120-213.eu-north-1.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Add the name of the secret that contains the SSH private key
          script: |
            sudo chmod -R 755 /var/www/html/

      - name: Copy Image to EC2 Instance
        uses: appleboy/scp-action@master
        with:
          host: ec2-16-16-120-213.eu-north-1.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Add the name of the secret that contains the SSH private key
          source: main.png
          target: /var/www/html/

      - name: Restart Apache2 on EC2 Instance
        uses: appleboy/ssh-action@master
        with:
          host: ec2-16-16-120-213.eu-north-1.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Add the name of the secret that contains the SSH private key
          script: sudo systemctl restart apache2
