name: Publish on EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy Image to EC2 Instance
        uses: appleboy/scp-action@master
        with:
          host: ec2-16-16-120-213.eu-north-1.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Add the name of the secret that contains the SSH private key
          source: main.png
          target: /var/www/html/

      - name: Set Ownership and Permissions on Image
        uses: appleboy/ssh-action@master
        with:
          host: ec2-16-16-120-213.eu-north-1.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Add the name of the secret that contains the SSH private key
          script: |
            sudo chown www-data:www-data /var/www/html/main.png
            sudo chmod 644 /var/www/html/main.png

      - name: Restart Apache2 on EC2 Instance
        uses: appleboy/ssh-action@master
        with:
          host: ec2-16-16-120-213.eu-north-1.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Add the name of the secret that contains the SSH private key
          script: sudo systemctl restart apache2
